### ISSUE TITLE
https only

### ISSUE THREAD

**Issue by PhillipSz** [snwh/computefreely#1]
Forward http to https. This side should represent that linux/free software stand for security! (you can use https://cert.startcom.org/?lang=en&app=100 to get a certificate.

**Comment by snwh** [comment]
It's not really necessary.

**Comment by PhillipSz** [comment]
http://www.computerworld.com/article/2861583/google-wants-to-turn-browser-signals-of-web-encryption-upside-down.html

**Comment by snwh** [comment]
But, there's no exchange of data that needs encryption.
