### ISSUE TITLE
new additions

### ISSUE THREAD

**Issue by baimafeima** [snwh/computefreely#10]
It would be great to add the following operating systems to your website: 
- Solus
- Tails
- Qubes

**Comment by snwh** [comment]
Hmm, good idea. Perhaps a category for security.

**Comment by rugk** [comment]
They are all there right now. This issue can be closed.

**Comment by MggMuggins** [comment]
Manjaro is a good option for Arch that's not quite so difficult. It's geared towards beginners and steady desktop users alike. I think it would make a good addition.

**Comment by snwh** [comment]
There is a whole page: https://computefreely.org/more 😉

**Comment by MggMuggins** [comment]
I'm fairly sure there's a typo in Tails.
