### ISSUE TITLE
Why is Fedora is "intermediate"?

### ISSUE THREAD

**Issue by catern** [snwh/computefreely#3]
The description on the Fedora homepage of the desktop product is "Fedora Workstation is a polished, easy to use operating system for laptop and desktop computers, with a complete set of tools and helpers for developers and makers of all kinds."
Fedora strives to be (and is, I think) easy to use and have minimal setup required.
Therefore I think Fedora should either be classed "beginner", or the entire system of classing things "beginner", "intermediate", "advanced" should be scrapped.
After all, Arch isn't really any more advanced than a deboostrap-based install of Debian or a yum-based install of Fedora.

**Comment by danshadeck** [comment]
I also agree that Fedora is a "beginner" class distro!

however I disagree with removing the difficulty ratings. 
@catern i think you are over estimating the ability of new comers. While i agree with the statement "After all, Arch isn't really any more advanced than a deboostrap-based install of Debian or a yum-based install of Fedora." i believe this is a statement that new comers will struggle with. Majority of them will have never had CLI experience... Not to say that they can't learn!

**Comment by snwh** [comment]
First, of course the website would say that, they're in the business of getting folks to use Fedora. Fedora is "intermediate" since its installer is fairly complicated (still) in spite of being graphical and it's still requires a bit of Linux knowledge to get around.

**Comment by snwh** [comment]
re: Arch: If I am required to have a second device to open up a wiki or to have printed off said wiki pages to install an OS and follow step-by-step instructions, inputting things to a command line then that's not beginner and then I have to intimately know how to use a complex command-line package manager to install further software, does not make it "easy"
