### ISSUE TITLE
Use Matomo?

### ISSUE THREAD

**Issue by rugk** [snwh/computefreely#30]
It seems currently you do not track visitor counts or so.

However, I guess it may be quite interesting for this site to do.
Of course, in a privacy-preserving way, i.e. do _not_ use Google Analytics, but good things like https://matomo.org/ (formerly Piwik), preferably self-hosted.

It may be interesting e.g. to see whether (and how much of a) spark there is when Win 7 support is ending (https://github.com/snwh/computefreely/issues/27) or whether other events increase site visits or so.
Just to get some insights in trends or so…

**Comment by snwh** [comment]
I'm not interested in tracking visitors at all in anyway nor am I interested in trends, so I will not even use FOSS analytics.
