### ISSUE TITLE
Domain expired

### ISSUE THREAD

**Issue by inputsh** [snwh/computefreely#6]
Any chance you could re-buy it? I liked this website a lot. Alternatively, I could buy it for you and re-direct it here.

**Comment by snwh** [comment]
I re-bought it yesterday actually. Odd that it's not back up.

**Comment by snwh** [comment]
Odd that it's not back up.

**Comment by inputsh** [comment]
Huh, I guess it took a while. It wasn't online here when I reported this issues (so, six hours ago), but now it is.

**Comment by snwh** [comment]
This repository isn't where the site is hosted. ;)
