### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by Secret-chest** [snwh/computefreely#73]
@snwh What happened to the Paper icon theme? Is it abandoned? It was my favorite theme. And Papirus sucks. It's too blue and the folders have that weird paper in them. Guess I have to make a fork of Papirus and add all the old Paper icons to it.

**Comment by snwh** [comment]
Yeah, I mean it's been 2+ years since I made significant updates to any icon themes. Should've been a sign I've moved onto other things and lost interest in maintaining icon themes. (Also, please don't file unrelated issues against my other repositories like this.)
