### ISSUE TITLE
general purpose vs specialist and independent vs community distros

### ISSUE THREAD

**Issue by baimafeima** [snwh/computefreely#9]
What do you think about recategorizing the existing operating systems into: 
- general purpose operating systems and specialist/niche distros (and add a few more of the latter)
- independent operating systems (Debian, Fedora, Solus, etc.) and community distributions and spin-offs (Ubuntu MATE, Ubuntu Budgie, Linux Mint, elementary, etc.)

**Comment by MggMuggins** [comment]
I'd like to see things like desktop environments explained as well. Look-and-feel is so integrated with the OS in most people's minds, so I feel like making newbies aware that they aren't stuck with a certain look and feel going with linux as they would with another OS.

**Comment by snwh** [comment]
Sorry I'm late, this can probably be achieved with tags on the rewritten site.

**Comment by snwh** [comment]
I think the thrust of this issue is covered by the present site, that is that desktop environment are explained a bit. Independence is kind-of addressed with the "based-on" section in each distro.
